### PR TITLE
Loading shapefile with additional explanation

### PR DESCRIPTION
**Pull request by mjones01**
I wanted to add extra information explaining what/why to initial code section about loading shapefiles. This could duplicate explanation in the raster section?

### CODE REVIEW

**Comment by lwasser** [comment]
Hey @jsta I am knitting via a script rather than in situ. it works just fine that way. I wanted to make the entire repo as operational as possible. If there is a way to fix that issue for local knitting that is perfect - please let me know! But right now the knitr script allows you to build the entire repo and then post it for final render.

http://data-lessons.github.io/NEON-R-Spatial-Vector/

KNITR Code:
https://github.com/data-lessons/NEON-R-Spatial-Vector/blob/gh-pages/knitr_code/knitRMD-2-MD.R

open to any and all ideas!

**Comment by lwasser** [comment]
hey @mjones01 thank you for the edits. can you please fix this

+Whenever adding a new file it is good coding practice to include what the file
+is and it source.  [In the initial what is the additional metadata added and
+why? ->add to description ]

There is a comment in here but also it is confusing. When you load a shapefile you have to specify
1. the directory and
2. the file name minus the extension. So i'm not sure what you mean by it's good coding practice to include those things??

Thank you for cleaning this up - and resubmitting.

**Comment by mjones01** [comment]
Should now be fixed. (I'm not sure what I was meaning there either).

**Comment by lwasser** [comment]
Thanks @mjones01  merging now. When you are done we can rebuild the entire directory!

**Pull request merged**
