### PR TITLE
fix line width comment and typo

### PR DESCRIPTION
**Pull request by jsta**
fixes item 1 of #97

### CODE REVIEW

**Comment by lwasser** [comment]
Thank you! I this is a great fix. I'm going to wait to merge it until i have time to rebuild the lessons which will likely be later today). :) If i don't do both at the same time i will forget to rebuild.

**Comment by lwasser** [comment]
Hey Guys - before we dig any further into this fix - can you please make sure you have the most current version of the data subset downloaded? I did a quick check and I think that the correct file is there in our data repo.

Link:  https://figshare.com/articles/Spatio_temporal_Series_Teaching_Data_Subsets/2009586/8

I'd like to figure out where the incorrect file is coming from!
Leah

**Comment by jsta** [comment]
Are you referring to `HARV_roads.shp`? I believe I downloaded it from the link in the lesson header [https://ndownloader.figshare.com/files/3708751](https://ndownloader.figshare.com/files/3708751) last Saturday (4/9).

**Comment by jsta** [comment]
I am going to go ahead and merge this. I think it's pretty clear that the first level will be the narrowest no matter the data version because the width vector is `c(1,2,3,4)` not `c(4,3,2,1)`

**Pull request merged**
